services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - db
    expose:
      - "5000"

  web:
    image: nginx:alpine
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8081:80"
    depends_on:
      - app

volumes:
  db-data:
